# Generated by Django 5.0.2 on 2024-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StyleAndBeautyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_description',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='master',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
